ALTER TYPE "StudyGroupStatus" ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE "StudyGroupStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

ALTER TABLE "StudyGroup" ALTER COLUMN "status" SET DEFAULT 'PENDING_REVIEW';
